### ISSUE TITLE
tensorflow版vot测试代码

### ISSUE THREAD

**Issue by GengMingjin2** [qimingyudaowenti/SiamFC-pytorch-learning#1]
大佬你好，我最近正在使用bilylee/SiamFC-TensorFlow这个版本的代码，想要在vot上进行测试其训练出来的模型的结果，但是我遇到一些代码问题，希望可以能从您这里学习一下。您这里能不能发我一份您当时在测试tensorflow版的siamfc时所用的vot_tracker的srcripts？我自己参考他人写的代码一直在报错，希望能找个正确的参考！如果可以的话万分感谢，我的邮箱是695185348@qq.com!如果不行的的话也希望能和您交流一下我现在遇到的问题。
谢谢！

**Comment by qimingyudaowenti** [comment]
下面是我搭配[bilylee/SiamFC-TensorFlow](https://github.com/bilylee/SiamFC-TensorFlow)的VOT接口python文件：
```python
import vot
import os.path as osp
import sys

import tensorflow as tf

CURRENT_DIR = osp.dirname(__file__)

sys.path.append(osp.join(CURRENT_DIR, '../../..'))

from inference import inference_wrapper
from inference.tracker_modify import Tracker
from utils.misc_utils import  load_cfgs

print('a')
handle = vot.VOT("rectangle")
selection = handle.region()

imagefile = handle.frame()

if not imagefile:
    sys.exit(0)


checkpoint = '/home/ubuntu/DeepLearningModel/SiamFC-TensorFlow-master/Logs/SiamFC/track_model_checkpoints/SiamFC-3s-color-pretrained'

model_config, _, track_config = load_cfgs(checkpoint)
track_config['log_level'] = 0

g = tf.Graph()
with g.as_default():
    model = inference_wrapper.InferenceWrapper()
    restore_fn = model.build_graph_from_config(model_config, track_config, checkpoint)
g.finalize()

gpu_options = tf.GPUOptions(allow_growth=True)
sess_config = tf.ConfigProto(gpu_options=gpu_options)

with tf.Session(graph=g, config=sess_config) as sess:
    restore_fn(sess)

    tracker = Tracker(sess, model,
                      model_config=model_config,
                      track_config=track_config,
                      first_bbox=selection,
                      first_frame=imagefile)

    while True:
        imagefile = handle.frame()
        if not imagefile:
            break

        predict_bbox = tracker.track(sess, imagefile)

        selection = selection._replace(x=predict_bbox.x,
                                       y=predict_bbox.y,
                                       width=predict_bbox.width,
                                       height=predict_bbox.height)

        handle.report(selection)
```
可以参考：[Performing evaluation with VOT toolkit](http://geyao1995.com/fight_against_vot_toolkit/#more)

**Comment by GengMingjin2** [comment]
谢谢大佬！我尝试了您的代码，发现需要对inference/tracker.py进行修改，于是我按照您这里的函数名字和参数修改了一个新的tracker_modify.py，这里我有几个问题：
**1、首先我没有成功，它提示一个如下的错误**：
CLIENT: Creating process /home/geng/anaconda3/envs/tensorflow/bin/python  -c "import sys; sys.path.append('/home/geng/project/SiamFC-TensorFlow-master'); import run_vot"
CLIENT: Working directory is /tmp/tp1ca94482_2301_47ea_9f93_d1e98701c083
CLIENT: Starting process
CLIENT: Setting up TraX with standard streams connection
@@TRAX:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=2" "trax.channels=color;" 
CLIENT: Tracker process ID: 29070
CLIENT: Connection with tracker established.
@@TRAX:initialize "file:///home/geng/project/vot-toolkit-master/sa/sequences/bag/color/00000001.jpg" "292.2300,128.3600,145.9600,132.4700" 
@@TRAX:state "292.2300,128.3600,145.9600,132.4700" 
Error || 和 && 运算符的操作数必须能够转换为逻辑标量值。
2019-05-17 16:23:12.439237: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-05-17 16:23:12.500549: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-05-17 16:23:12.500768: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1070 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.47GiB
2019-05-17 16:23:12.500778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
@@TRAX:frame "**file:///home/geng/project/vot-toolkit-master/sa/sequences/bag/color/00000002.jpg**" 
@@TRAX:quit 
Traceback (most recent call last):
CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Trying to stop process using protocol.
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited (exit code 1)
**Tracker execution interrupted: Did not receive response.**
这个问题和我自己参考其他人的代码写出来的scripts有同样的错误，另外一个大佬说不应该使用anaconda创造的python路径，应该使用系统的python，我这里不清楚...您当时的测试环境是系统的还是利用anaconda创建的虚拟工程环境？
**2、关于tracker_modify.py的修改**，我这里的理解是每次都是对输入的那一帧(imagefile)进行跟踪处理，而不是当前整个视频序列，所以Tracker.track()函数的只对输入的那一帧做bbox的预测，然后输出的跟踪结果只有一个reported_bbox（而不是其原来的reported_bboxs），最后改成vot需要的selection的格式作为report的输入？
先谢过大佬的时间了！

**Comment by qimingyudaowenti** [comment]
0. 我把`Tracker.track()`改为对单帧的预测：
```python
    def track(self, sess, next_frame):
        """Runs tracking on a single image sequence."""
        bbox_feed = [self.current_target_state.bbox.y, self.current_target_state.bbox.x,
                     self.current_target_state.bbox.height, self.current_target_state.bbox.width]
        input_feed = [next_frame, bbox_feed]

        outputs, metadata = self.siamese_model.inference_step(sess, input_feed)
        search_scale_list = outputs['scale_xs']
        response = outputs['response']
        response_size = response.shape[1]

        # Choose the scale whole response map has the highest peak
        if self.num_scales > 1:
            response_max = np.max(response, axis=(1, 2))
            penalties = self.track_config['scale_penalty'] * np.ones((self.num_scales))
            current_scale_idx = int(get_center(self.num_scales))
            penalties[current_scale_idx] = 1.0
            response_penalized = response_max * penalties
            best_scale = np.argmax(response_penalized)
        else:
            best_scale = 0

        response = response[best_scale]

        with np.errstate(all='raise'):    # Raise error if something goes wrong
            response = response - np.min(response)
            response = response / np.sum(response)

        if self.window is None:
            window = np.dot(np.expand_dims(np.hanning(response_size), 1),
                                            np.expand_dims(np.hanning(response_size), 0))
            self.window = window / np.sum(window)    # normalize window
        window_influence = self.track_config['window_influence']
        response = (1 - window_influence) * response + window_influence * self.window

        # Find maximum response
        r_max, c_max = np.unravel_index(response.argmax(),response.shape)

        # Convert from crop-relative coordinates to frame coordinates
        p_coor = np.array([r_max, c_max])
        # displacement from the center in instance final representation ...
        disp_instance_final = p_coor - get_center(response_size)
        # ... in instance feature space ...
        upsample_factor = self.track_config['upsample_factor']
        disp_instance_feat = disp_instance_final / upsample_factor
        # ... Avoid empty position ...
        r_radius = int(response_size / upsample_factor / 2)
        disp_instance_feat = np.maximum(np.minimum(disp_instance_feat, r_radius), -r_radius)
        # ... in instance input ...
        disp_instance_input = disp_instance_feat * self.model_config['embed_config']['stride']
        # ... in instance original crop (in frame coordinates)
        disp_instance_frame = disp_instance_input / search_scale_list[best_scale]
        # Position within frame in frame coordinates
        y = self.current_target_state.bbox.y
        x = self.current_target_state.bbox.x
        y += disp_instance_frame[0]
        x += disp_instance_frame[1]

        # Target scale damping and saturation
        target_scale = self.current_target_state.bbox.height / self.original_target_height
        search_factor = self.search_factors[best_scale]
        scale_damp = self.track_config['scale_damp']    # damping factor for scale update
        target_scale *= ((1 - scale_damp) * 1.0 + scale_damp * search_factor)
        target_scale = np.maximum(0.2, np.minimum(5.0, target_scale))

        # Some book keeping
        height = self.original_target_height * target_scale
        width = self.original_target_width * target_scale
        self.current_target_state.bbox = Rectangle(x, y, width, height)
        self.current_target_state.scale_idx = best_scale
        self.current_target_state.search_pos = self.search_center + disp_instance_input

        assert 0 <= self.current_target_state.search_pos[0] < self.x_image_size, \
            'target position in feature space should be no larger than input image size'
        assert 0 <= self.current_target_state.search_pos[1] < self.x_image_size, \
            'target position in feature space should be no larger than input image size'

        reported_bbox = convert_bbox_format(self.current_target_state.bbox, 'top-left-based')

        return reported_bbox
```
1. 参考我当时调试VOT的经验：[如何配置VOT toolkit请看这里](http://geyao1995.com/fight_against_vot_toolkit/#more)，是可以用conda虚拟环境进行测评的。
2. 对的，接口就是对单帧预测，返回bbox。

**Comment by qimingyudaowenti** [comment]
由于时间比较久远，为了改成单帧预测，对于`Tracker`类还有哪些改动我已经记不清了。在使用VOT toolkit过程中，我遇到问题通常会在python接口文件中加入`print`进行调试，对应信息会在MATLAB窗口中显示（有一定几率，不会100%显示，多重复运行几次吧）。

**Comment by GengMingjin2** [comment]
好的，谢谢大佬！！非常感谢！

**Comment by GengMingjin2** [comment]
好了大佬！终于调通了！不是环境的问题，是单帧做预测时我没有处理好current_target_state的更新！太感谢大佬了！谢谢谢谢！
